name: Automated Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  code-review:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Print environment variables for debugging
      run: |
        echo "PR_NUMBER: $PR_NUMBER"
      env:
        PR_NUMBER: ${{ github.event.pull_request.number }}

    - name: Run code review script
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        GPT_API_KEY: ${{ secrets.GPT_API_KEY }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
      run: python code_review_script.py
